import type { LessonMeta, PhaseInfo } from '../types/lesson';

// All lesson metadata — used by Sidebar and routing
export const LESSONS: LessonMeta[] = [
  {
    id: '01-python-fundamentals',
    number: 1,
    title: 'Python Fundamentals',
    description: 'So sánh Python ↔ TypeScript, cú pháp, functions, classes, type hints',
    phase: 'phase-1',
    estimatedTime: '2-3 ngày',
    prerequisites: [],
  },
  {
    id: '02-pandas-data-processing',
    number: 2,
    title: 'Pandas Data Processing',
    description: 'DataFrame, đọc/ghi dữ liệu, lọc, groupby, xử lý Zeek conn.log',
    phase: 'phase-1',
    estimatedTime: '2-3 ngày',
    prerequisites: ['01-python-fundamentals'],
  },
  {
    id: '03-numpy-statistics',
    number: 3,
    title: 'NumPy & Statistics',
    description: 'Array operations, thống kê, normalization, broadcasting',
    phase: 'phase-1',
    estimatedTime: '2-3 ngày',
    prerequisites: ['02-pandas-data-processing'],
  },
  {
    id: '04-ml-fundamentals',
    number: 4,
    title: 'ML Fundamentals',
    description: 'Supervised/Unsupervised, workflow, train/test, metrics, overfitting',
    phase: 'phase-1',
    estimatedTime: '3-4 ngày',
    prerequisites: ['03-numpy-statistics'],
  },
  {
    id: '05-sklearn-anomaly-detection',
    number: 5,
    title: 'Scikit-learn Anomaly Detection',
    description: 'Isolation Forest, Pipeline, threshold tuning, model serialization',
    phase: 'phase-2',
    estimatedTime: '3-4 ngày',
    prerequisites: ['04-ml-fundamentals'],
  },
  {
    id: '06-network-feature-engineering',
    number: 6,
    title: 'Feature Engineering',
    description: 'Zeek conn.log features, encoding, IP aggregation, time-window',
    phase: 'phase-2',
    estimatedTime: '3-4 ngày',
    prerequisites: ['05-sklearn-anomaly-detection'],
  },
  {
    id: '07-fastapi-ml-engine',
    number: 7,
    title: 'FastAPI ML Engine',
    description: 'REST API, Pydantic schemas, model serving, Docker deployment',
    phase: 'phase-2',
    estimatedTime: '3-4 ngày',
    prerequisites: ['06-network-feature-engineering'],
  },
  {
    id: '08-elasticsearch-python-client',
    number: 8,
    title: 'Elasticsearch Python Client',
    description: 'Search/Scroll API, aggregation, tích hợp ML pipeline',
    phase: 'phase-2',
    estimatedTime: '2-3 ngày',
    prerequisites: ['07-fastapi-ml-engine'],
  },
  {
    id: '09-supervised-learning',
    number: 9,
    title: 'Supervised Learning',
    description: 'Random Forest multi-class, feature importance, cross-validation',
    phase: 'phase-3',
    estimatedTime: '3-4 ngày',
    prerequisites: ['08-elasticsearch-python-client'],
  },
  {
    id: '10-autoencoder-anomaly-detection',
    number: 10,
    title: 'Autoencoder Anomaly Detection',
    description: 'PyTorch basics, reconstruction error, so sánh IF/RF/AE',
    phase: 'phase-3',
    estimatedTime: '4-5 ngày',
    prerequisites: ['09-supervised-learning'],
  },
  {
    id: '11-mlops-practices',
    number: 11,
    title: 'MLOps Practices',
    description: 'Model versioning, retraining, monitoring, data drift',
    phase: 'phase-3',
    estimatedTime: '2-3 ngày',
    prerequisites: ['10-autoencoder-anomaly-detection'],
  },
  // ─── Phase 4: ML Workflow Foundations ───
  {
    id: '12-eda-data-analysis',
    number: 12,
    title: 'EDA & Data Analysis',
    description: 'Khám phá dữ liệu: distribution, correlation, missing values trước khi train',
    phase: 'phase-4',
    estimatedTime: '2-3 ngày',
    prerequisites: ['11-mlops-practices'],
  },
  {
    id: '13-data-quality-imbalanced',
    number: 13,
    title: 'Data Quality & Imbalanced Data',
    description: 'SMOTE, class weights, PR-AUC — xử lý 99% normal / 1% anomaly',
    phase: 'phase-4',
    estimatedTime: '2-3 ngày',
    prerequisites: ['12-eda-data-analysis'],
  },
  {
    id: '14-hyperparameter-tuning',
    number: 14,
    title: 'Hyperparameter Tuning',
    description: 'Grid Search, Random Search, Optuna, Cross-validation đúng cách',
    phase: 'phase-4',
    estimatedTime: '2-3 ngày',
    prerequisites: ['13-data-quality-imbalanced'],
  },
  // ─── Phase 5: Model Mastery ───
  {
    id: '15-model-comparison-unsupervised',
    number: 15,
    title: 'Model Comparison: Unsupervised',
    description: 'IF vs LOF vs OCSVM vs DBSCAN vs Elliptic Envelope vs Z-score vs Autoencoder',
    phase: 'phase-5',
    estimatedTime: '3-4 ngày',
    prerequisites: ['14-hyperparameter-tuning'],
  },
  {
    id: '16-gradient-boosting',
    number: 16,
    title: 'XGBoost & Gradient Boosting',
    description: 'Gradient boosting vs RF, XGBoost vs LightGBM, multi-class classification',
    phase: 'phase-5',
    estimatedTime: '3-4 ngày',
    prerequisites: ['15-model-comparison-unsupervised'],
  },
  {
    id: '17-shap-explainability',
    number: 17,
    title: 'SHAP & Model Explainability',
    description: 'Tại sao alert X là anomaly? Global vs Local explanation',
    phase: 'phase-5',
    estimatedTime: '2-3 ngày',
    prerequisites: ['16-gradient-boosting'],
  },
  {
    id: '18-lstm-temporal',
    number: 18,
    title: 'LSTM & Temporal Anomaly Detection',
    description: 'Sequential patterns trong network traffic, PyTorch LSTM',
    phase: 'phase-5',
    estimatedTime: '4-5 ngày',
    prerequisites: ['17-shap-explainability'],
  },
  {
    id: '19-capstone-project',
    number: 19,
    title: 'Capstone Project',
    description: 'End-to-end: raw Zeek logs → EDA → train → SHAP → FastAPI → MLOps',
    phase: 'phase-5',
    estimatedTime: '5-7 ngày',
    prerequisites: ['18-lstm-temporal'],
  },
];

export const PHASES: PhaseInfo[] = [
  {
    id: 'phase-1',
    title: 'Phase 1',
    subtitle: 'Python & Data Science',
    color: 'var(--color-phase-1)',
    lessons: LESSONS.filter((l) => l.phase === 'phase-1'),
  },
  {
    id: 'phase-2',
    title: 'Phase 2',
    subtitle: 'Applied ML for Security',
    color: 'var(--color-phase-2)',
    lessons: LESSONS.filter((l) => l.phase === 'phase-2'),
  },
  {
    id: 'phase-3',
    title: 'Phase 3',
    subtitle: 'Advanced ML & MLOps',
    color: 'var(--color-phase-3)',
    lessons: LESSONS.filter((l) => l.phase === 'phase-3'),
  },
  {
    id: 'phase-4',
    title: 'Phase 4',
    subtitle: 'ML Workflow Foundations',
    color: 'var(--color-phase-4)',
    lessons: LESSONS.filter((l) => l.phase === 'phase-4'),
  },
  {
    id: 'phase-5',
    title: 'Phase 5',
    subtitle: 'Model Mastery',
    color: 'var(--color-phase-5)',
    lessons: LESSONS.filter((l) => l.phase === 'phase-5'),
  },
];

export const LESSON_BY_ID = new Map(LESSONS.map((l) => [l.id, l]));
