import type { LessonMeta, PhaseInfo } from '../types/lesson';

// All lesson metadata — used by Sidebar and routing
export const LESSONS: LessonMeta[] = [
  {
    id: '01-python-fundamentals',
    number: 1,
    title: 'Python Fundamentals',
    description: 'So sánh Python ↔ TypeScript, cú pháp, functions, classes, type hints',
    phase: 'phase-1',
    estimatedTime: '2-3 ngày',
    prerequisites: [],
  },
  {
    id: '02-pandas-data-processing',
    number: 2,
    title: 'Pandas Data Processing',
    description: 'DataFrame, đọc/ghi dữ liệu, lọc, groupby, xử lý Zeek conn.log',
    phase: 'phase-1',
    estimatedTime: '2-3 ngày',
    prerequisites: ['01-python-fundamentals'],
  },
  {
    id: '03-numpy-statistics',
    number: 3,
    title: 'NumPy & Statistics',
    description: 'Array operations, thống kê, normalization, broadcasting',
    phase: 'phase-1',
    estimatedTime: '2-3 ngày',
    prerequisites: ['02-pandas-data-processing'],
  },
  {
    id: '04-ml-fundamentals',
    number: 4,
    title: 'ML Fundamentals',
    description: 'Supervised/Unsupervised, workflow, train/test, metrics, overfitting',
    phase: 'phase-1',
    estimatedTime: '3-4 ngày',
    prerequisites: ['03-numpy-statistics'],
  },
  {
    id: '05-sklearn-anomaly-detection',
    number: 5,
    title: 'Scikit-learn Anomaly Detection',
    description: 'Isolation Forest, Pipeline, threshold tuning, model serialization',
    phase: 'phase-2',
    estimatedTime: '3-4 ngày',
    prerequisites: ['04-ml-fundamentals'],
  },
  {
    id: '06-network-feature-engineering',
    number: 6,
    title: 'Feature Engineering',
    description: 'Zeek conn.log features, encoding, IP aggregation, time-window',
    phase: 'phase-2',
    estimatedTime: '3-4 ngày',
    prerequisites: ['05-sklearn-anomaly-detection'],
  },
  {
    id: '07-fastapi-ml-engine',
    number: 7,
    title: 'FastAPI ML Engine',
    description: 'REST API, Pydantic schemas, model serving, Docker deployment',
    phase: 'phase-2',
    estimatedTime: '3-4 ngày',
    prerequisites: ['06-network-feature-engineering'],
  },
  {
    id: '08-elasticsearch-python-client',
    number: 8,
    title: 'Elasticsearch Python Client',
    description: 'Search/Scroll API, aggregation, tích hợp ML pipeline',
    phase: 'phase-2',
    estimatedTime: '2-3 ngày',
    prerequisites: ['07-fastapi-ml-engine'],
  },
  {
    id: '09-supervised-learning',
    number: 9,
    title: 'Supervised Learning',
    description: 'Random Forest multi-class, feature importance, cross-validation',
    phase: 'phase-3',
    estimatedTime: '3-4 ngày',
    prerequisites: ['08-elasticsearch-python-client'],
  },
  {
    id: '10-autoencoder-anomaly-detection',
    number: 10,
    title: 'Autoencoder Anomaly Detection',
    description: 'PyTorch basics, reconstruction error, so sánh IF/RF/AE',
    phase: 'phase-3',
    estimatedTime: '4-5 ngày',
    prerequisites: ['09-supervised-learning'],
  },
  {
    id: '11-mlops-practices',
    number: 11,
    title: 'MLOps Practices',
    description: 'Model versioning, retraining, monitoring, data drift',
    phase: 'phase-3',
    estimatedTime: '2-3 ngày',
    prerequisites: ['10-autoencoder-anomaly-detection'],
  },
];

export const PHASES: PhaseInfo[] = [
  {
    id: 'phase-1',
    title: 'Phase 1',
    subtitle: 'Python & Data Science',
    color: 'var(--color-phase-1)',
    lessons: LESSONS.filter((l) => l.phase === 'phase-1'),
  },
  {
    id: 'phase-2',
    title: 'Phase 2',
    subtitle: 'Applied ML for Security',
    color: 'var(--color-phase-2)',
    lessons: LESSONS.filter((l) => l.phase === 'phase-2'),
  },
  {
    id: 'phase-3',
    title: 'Phase 3',
    subtitle: 'Advanced ML & MLOps',
    color: 'var(--color-phase-3)',
    lessons: LESSONS.filter((l) => l.phase === 'phase-3'),
  },
];

export const LESSON_BY_ID = new Map(LESSONS.map((l) => [l.id, l]));
